name: slack_github_action

on:
  push:
    branches:
      - main

jobs:
  slack_notifier:
    runs-on: self-hosted

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/  # Assuming jfrog is in the current directory

      - name: Build Maven project
        run: |
          mvn clean install
          export MAVEN_EXIT_CODE=$?

      - name: Generate code coverage report
        run: |
          mvn jacoco:report

      - name: Publish code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco/index.html
          
      - uses: actions/checkout@v2
      - name: SonarQube Scan
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_GITHUBACTION }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

      - name: Set JFrog CLI Path
        run: |
          export PATH=$PATH:/usr/local/bin

      - name: Push Artifacts to JFrog
        run: |
                  jfrog rt u target/*.jar artifacts_pocs-libs-snapshot-local/ --url=https://shadabjfrog.jfrog.io/artifactory/githubactionpoc10-libs-snapshot-local/ --access-token=eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJvbnpIRjl3bXRGZE1jaGdLbEdEbEcxRFhyUGs2RlpxSDIwRWMwWlo2V3FBIn0.eyJzdWIiOiJqZmFjQDAxaHIyeGIyYmdmeTA4MTl3NnRwY3owOWV4L3VzZXJzL3NoYWRhYm1hbGlrc0BjeWJhZ2UuY29tIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9ucy9hZG1pbiIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDFocjJ4YjJiZ2Z5MDgxOXc2dHBjejA5ZXgiLCJpYXQiOjE3MDk1NTIwMDgsImp0aSI6IjkyYmNlOGVmLWQzNDMtNGU3ZS05ZDRkLTFmZDVkYzM2YWY4ZSJ9.g_UzURwmOLEfVUgBbNzx1lwHLXbMNWqO2CJ585n37r9IYtiEFQtrzJ_MfiO7xq57pFsYZfFvjAf6_EU0Xd__0Hc7s1SQs_TIY0lXVwAC1Aro6iHfIaD8fmDoPlYb2jJ0D7Fcv2g2KfbQbC3hbAdFFfCKQ-O1fjSiNysAQy1kMCnu2aR_mtvAapUhXS0sAqS3Qo0f8UHJI0A6eNkmpPY9AgKgQ37cqRqhFmeqsY5xd0SeYcmoXLHeE6KQMdo3l03DlQ1LslTUnnlOt9FJpyOx7YCa3RHtd0YNZuNJHo3Zf3uPlECVuxUVlM04pWA0nFuSWWLaccCU5_cuGq-Sb8dKtw

        # env:
        #   JFROG_ACCESS_TOKEN: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJHbGs3b1N0VU1YSGxNdTlzbUZZSVdld0liR0MwSXA2YWhJcEhaM3RUcFBvIn0.eyJzdWIiOiJqZmFjQDAxaHFrNjAxcHhjdGVtMW5qYXJjcWUxY3liL3VzZXJzL29ua2Fya29AY3liYWdlLmNvbSIsInNjcCI6ImFwcGxpZWQtcGVybWlzc2lvbnMvYWRtaW4iLCJhdWQiOiIqQCoiLCJpc3MiOiJqZmZlQDAxaHFrNjAxcHhjdGVtMW5qYXJjcWUxY3liIiwiaWF0IjoxNzA5MTExODM1LCJqdGkiOiIzMTNkMjFkZi1mNDE2LTQxM2MtYmJlMC1lMTI1NTlmNDAwNTAifQ.3s9yioc5sgDsvdBLE_YGjXzrdZm2hr90WTAanmIwshFVb-CPzRyH1Nv-rCYxuqgxbHQdobM6616kmwfKezd9anBuLSLuvw5Jx5OK7wQAjo4Qktx9kRMs5yd_DKDn8-PBlB9FGl0x25fDQwXUaSHMyX9ecQoon0NBJH5z5_X8GDH5rUfsVZ9DS8Bq0PiA203yDGQytdp70u-ISk-eQpQwIcUhsLJqw-CM4spBKz01k6I6QvG2kUfjt8CqyOXvCQsGsCmTowsrf02PSnDeJBFHCfk1TkCOtH0BY3rcTDDcWkXX1R-YfRMbL5WCMBjRHKl8S3qTBngPK5xq0rqXPO3vZw
          

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven project built successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKEN }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven build failed. Please check the build logs for details."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKEN }}
